server:
    port: 8081 # ??

spring:
    application:
        name: ms-diners # ???
    # ???
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root123456
        url: jdbc:mysql://127.0.0.1:3306/db_imooc_redis?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    # Redis
    redis:
        port: 6379
        host: 127.0.0.1
        timeout: 3000
        password: 123456
    # swagger
    swagger:
        base-package: com.imooc.diners
        title: ????????API????

# Oauth2 ?????
oauth2:
    client:
        client-id: appId
        secret: 123456
        grant_type: password
        scope: api

# oauth2 ????
service:
    name:
        ms-oauth-server: http://ms-oauth2-server/

# ?? Eureka Server ????
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
    client:
        service-url:
            defaultZone: http://localhost:8080/eureka/

# Mybatis
mybatis:
    configuration:
        map-underscore-to-camel-case: true # ??????

logging:
    pattern:
        console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'